# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='organization',
            new_name='name',
        ),
        migrations.AddField(
            model_name='work',
            name='desc',
            field=models.TextField(default='', verbose_name='Описание деятельности компании'),
            preserve_default=False,
        ),
    ]
