# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMeApp', '0002_auto_20160704_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='region',
        ),
    ]
