# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMeApp', '0003_remove_work_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='duties',
        ),
        migrations.AddField(
            model_name='work',
            name='logo',
            field=models.CharField(default='', max_length=64, verbose_name='Логотп компании'),
            preserve_default=False,
        ),
    ]
