# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMeApp', '0004_auto_20160704_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Учебное заведение')),
                ('site', models.CharField(blank=True, max_length=64, verbose_name='Сайт')),
                ('faculty', models.TextField(verbose_name='Факультет')),
                ('specialty', models.TextField(verbose_name='Специальность')),
                ('degree', models.CharField(max_length=128, verbose_name='Уровень образования')),
                ('date_start', models.PositiveIntegerField(default=1, verbose_name='Дата начала обучения')),
                ('date_finish', models.PositiveIntegerField(default=1, verbose_name='Дата завершения обучения')),
                ('logo', models.CharField(blank=True, max_length=64, verbose_name='Логотп')),
            ],
        ),
        migrations.AlterField(
            model_name='work',
            name='logo',
            field=models.CharField(blank=True, max_length=64, verbose_name='Логотп компании'),
        ),
    ]
