# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMeApp', '0005_auto_20160704_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.TextField(verbose_name='Учебное заведение'),
        ),
    ]
