# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 09:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMeApp', '0007_auto_20160704_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='period',
        ),
        migrations.AddField(
            model_name='work',
            name='date_finish',
            field=models.DateField(default=datetime.datetime(2016, 7, 4, 9, 57, 41, 148338, tzinfo=utc), verbose_name='Дата завершения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2016, 7, 4, 9, 57, 54, 706774, tzinfo=utc), verbose_name='Дата начала'),
            preserve_default=False,
        ),
    ]
