# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMeApp', '0010_auto_20160704_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('ico_fa', models.CharField(blank=True, max_length=64, verbose_name='Иконка (FA)')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birthday', models.DateField(verbose_name='Дата рождения')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=32, verbose_name='Отчество')),
                ('city_birthday', models.CharField(max_length=64, verbose_name='Место рождения')),
                ('hobbies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AboutMeApp.Hobby')),
            ],
        ),
    ]
