# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMeApp', '0011_hobby_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='hobbies',
            field=models.ManyToManyField(to='AboutMeApp.Hobby'),
        ),
    ]
