# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMeApp', '0012_auto_20160704_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='city_birthday',
            new_name='place_birthday',
        ),
    ]
